name: Gitleaks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure full history so gitleaks can diff previous commit
      - name: gitleaks
        uses: zricethezav/gitleaks-action@v2
